In [1]:
import numpy as np

#### Vector Operations

In [2]:
u = np.array([1, 2, 3])

print("u + 10 =", u + 10)
print("u * 10 =", u * 10)
print("u / 10 =", u / 10)

u + 10 = [11 12 13]
u * 10 = [10 20 30]
u / 10 = [0.1 0.2 0.3]


#### Multiplication

In [3]:
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
u.shape

(3,)

In [4]:
def vector_vector_multiplication(u, v):
    assert u.shape == v.shape, "Vectors must have the same shape"
    
    n = u.shape[0]  # Number of elements in the vectors
    result = 0
    
    for i in range(n):
        result += u[i] * v[i]
        
    return result

In [5]:
vector_vector_multiplication(u, v)

np.int64(32)

In [6]:
def matrix_vector_multiplication(A, u):
    assert A.shape[1] == u.shape[0], "Incompatible shapes for matrix-vector multiplication"
    
    m = A.shape[0]  # Number of rows in the matrix
    n = A.shape[1]  # Number of columns in the matrix
    result = np.zeros(m)
    
    for i in range(m):
        for j in range(n):
            result[i] += A[i, j] * u[j]
            
    return result

In [7]:
U = np.array([[1, 2, 3], [4, 5, 6]])
matrix_vector_multiplication(U, u)

array([14., 32.])

In [8]:
# Dot product implementation
def matrix_matrix_multiplication(A, B):
    assert A.shape[1] == B.shape[0], "Incompatible shapes for matrix-matrix multiplication"
    
    num_rows = A.shape[0]
    num_cols = B.shape[1]
    
    results = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        bi = B[:, i]  # Get the i-th column of B
        Abi = matrix_vector_multiplication(A, bi)  # Multiply A with the i-th column of B
        results[:, i] = Abi  # Store the result in the i-th column of the results matrix
        
    return results

In [9]:
B = np.array([[7, 8], [9, 10], [11, 12]])
matrix_matrix_multiplication(U, B)

array([[ 58.,  64.],
       [139., 154.]])

In [10]:
# Using NumPy's built-in functions for matrix multiplication
np.dot(U, B)

array([[ 58,  64],
       [139, 154]])

#### Identity Matrix

In [11]:
I = np.eye(3)  # Identity matrix of size 3x3
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
U

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
U.dot(I)  # Multiplying U with the identity matrix should return U

array([[1., 2., 3.],
       [4., 5., 6.]])

#### Inverse

In [19]:
U = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 11]])
U

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 11]])

In [20]:
U_inv = np.linalg.inv(U)
U_inv   

array([[-1.16666667, -0.33333333,  0.5       ],
       [ 0.33333333,  1.66666667, -1.        ],
       [ 0.5       , -1.        ,  0.5       ]])

In [21]:
U.dot(U_inv)  # This should return the identity matrix

array([[ 1.00000000e+00,  0.00000000e+00,  2.77555756e-16],
       [-4.44089210e-16,  1.00000000e+00,  1.11022302e-16],
       [-1.11022302e-15,  0.00000000e+00,  1.00000000e+00]])

In [23]:
U = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Can't compute the inverse of a matrix if it is singular (determinant is zero). Let's check the determinant of U:
det_U = np.linalg.det(U)
det_U

np.float64(0.0)

In [24]:
try:
    U_inv = np.linalg.inv(U)
except np.linalg.LinAlgError as e:
    print("Error:", e)

Error: Singular matrix
