# Intro to NumPy

In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/home/omer/projects/ml-zoomcamp/.venv/lib/python3.12/site-packages/numpy/__init__.py'>

### Creating Arrays

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 5) # Array of 10 elements, all set to 5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [7]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [8]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5])

In [9]:
np.arange(3, 10) # Array of integers from 3 to 9

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0, 1, 5) # Array of 5 evenly spaced numbers between 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
# Converting list to numpy array
list1 = [1, 2, 3, 4, 5]
array1 = np.array(list1)
array1

array([1, 2, 3, 4, 5])

### Multidimensional Arrays

In [13]:
np.zeros((3, 2)) # 10 rows, 2 columns

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
n = np.array([[1, 2, 3], [4, 5, 6]])
n

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
n[0, 1] = 100
n

array([[  1, 100,   3],
       [  4,   5,   6]])

In [16]:
n[1] = [7, 8, 9]
n

array([[  1, 100,   3],
       [  7,   8,   9]])

In [17]:
n[:, 1] = 99 # All rows, second column 
n

array([[ 1, 99,  3],
       [ 7, 99,  9]])

### Generating Random Arrays

In [18]:
np.random.seed(2) # Set the random seed for reproducibility
random_array = np.random.rand(3, 2) # 3 rows, 2 columns
random_array

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482]])

In [19]:
normal_distribution_array = np.random.randn(3, 2) # 3 rows, 2 columns
normal_distribution_array

array([[ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761],
       [ 0.55145404,  2.29220801]])

In [22]:
random_integers_array = np.random.randint(low=0, high=10, size=(3, 2)) # 3 rows, 2 columns, random integers between 0 and 9
random_integers_array

array([[3, 9],
       [2, 0],
       [4, 2]])

### Array Operations

#### Element-wise Operations

In [24]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr2 = arr1 + 10
arr2

array([[11, 12, 13],
       [14, 15, 16]])

In [26]:
arr2 / arr1

array([[11.        ,  6.        ,  4.33333333],
       [ 3.5       ,  3.        ,  2.66666667]])

#### Comparison Operations

In [27]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
arr1 > 3

array([[False, False, False],
       [ True,  True,  True]])

In [30]:
arr2 = np.array([[0, 2, 2], [10, 4, 12]])
arr2

array([[ 0,  2,  2],
       [10,  4, 12]])

In [31]:
arr1 > arr2

array([[ True, False,  True],
       [False,  True, False]])

In [32]:
arr1[arr1 > arr2]

array([1, 3, 5])

#### Summary Operations

In [33]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
min_value = np.min(arr1)
max_value = np.max(arr1)
sum_value = np.sum(arr1)
mean_value = np.mean(arr1)
std_dev_value = np.std(arr1)

print("Minimum value:", min_value)
print("Maximum value:", max_value)
print("Sum of all elements:", sum_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev_value)

Minimum value: 1
Maximum value: 6
Sum of all elements: 21
Mean value: 3.5
Standard deviation: 1.707825127659933
